# Autogenerated wrapper script for vte_jll for i686-linux-gnu-cxx03
export libvte

using GTK4_jll
using Libtiff_jll
using GnuTLS_jll
JLLWrappers.@generate_wrapper_header("vte")
JLLWrappers.@declare_library_product(libvte, "libvte-2.91-gtk4.so.0")
function __init__()
    JLLWrappers.@generate_init_header(GTK4_jll, Libtiff_jll, GnuTLS_jll)
    JLLWrappers.@init_library_product(
        libvte,
        "lib/libvte-2.91-gtk4.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
